function calculator(){var O='bootstrap',P='begin',Q='gwt.codesvr.calculator=',R='gwt.codesvr=',S='calculator',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='readystatechange',fb=10,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='calculator::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='calculator.nocache.js',Ib='base',Jb='//',Kb='gxt.device',Lb='tablet',Mb='desktop',Nb=2,Ob='gxt.user.agent',Pb='edge/',Qb='edge',Rb='chrome',Sb='trident',Tb='msie',Ub=11,Vb='ie11',Wb='ie10',Xb=9,Yb='ie9',Zb=8,$b='ie8',_b='safari',ac='version/3',bc='safari3',cc='version/4',dc='safari4',ec='safari5',fc='gecko',gc='rv:1.8',hc='gecko1_8',ic='gecko1_9',jc='adobeair',kc='air',lc=3,mc=4,nc=5,oc=6,pc=7,qc='user.agent',rc='webkit',sc='user.agent.os',tc='gx',uc='t',vc='t 4.0',wc='.3',xc='u=',yc='&p=',zc='&v=',Ac='//ua',Bc='p.sen',Cc='cha.c',Dc='om/pi',Ec='ng.g',Fc='if?',Gc='macintosh',Hc='mac os x',Ic='mac',Jc='linux',Kc='windows',Lc='win32',Mc='unknown',Nc='selectingPermutation',Oc='calculator.devmode.js',Pc="GWT module 'calculator' may need to be (re)compiled",Qc=':',Rc='.cache.js',Sc='link',Tc='rel',Uc='stylesheet',Vc='href',Wc='loadExternalRefs',Xc='gwt/standard/standard.css',Yc='reset.css',Zc='end',$c='http:',_c='file:',ad='_gwt_dummy_',bd='__gwtDevModeHook:calculator',cd='Ignoring non-whitelisted Dev Mode URL: ',dd=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
calculator.__sendStats=r;calculator.__moduleName=S;calculator.__errFn=null;calculator.__moduleBase=U;calculator.__softPermutationId=V;calculator.__computePropValue=null;calculator.__getPropMap=null;calculator.__installRunAsyncCode=function(){};calculator.__gwtStartLoadingFragment=function(){return null};calculator.__gwt_isKnownPropertyValue=function(){return false};calculator.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};calculator.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[calculator.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){d()},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
calculator.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(calculator.__errFn){n.onerror=function(){calculator.__errFn(S,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
calculator.__startLoadingFragment=function(a){return D(a)};calculator.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,bb);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;calculator.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return calculator.__moduleBase+a}
function F(){var g=[];var h=V;var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){var a=navigator.userAgent;if(a.match(/Android/i)){return Lb}else if(a.match(/BlackBerry/i)){return Lb}else if(a.match(/iPhone|iPad|iPod/i)){return Lb}else if(a.match(/IEMobile/i)){return Lb}else if(a.match(/Tablet PC/i)){return Lb}return Mb};i[Kb]={'desktop':V,'phone':W,'tablet':Nb};j[Ob]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Pb)!=-1)return Qb;if(a.indexOf(Rb)!=-1)return Rb;if(a.indexOf(Sb)!=-1||a.indexOf(Tb)!=-1){if(p.documentMode>=Ub)return Vb;if(p.documentMode>=fb)return Wb;if(p.documentMode>=Xb)return Yb;if(p.documentMode>=Zb)return $b;return Wb}if(a.indexOf(_b)!=-1){if(a.indexOf(ac)!=-1)return bc;if(a.indexOf(cc)!=-1)return dc;return ec}if(a.indexOf(fc)!=-1){if(a.indexOf(gc)!=-1)return hc;return ic}if(a.indexOf(jc)!=-1)return kc;return null};i[Ob]={'air':V,'chrome':W,'edge':Nb,'gecko1_8':lc,'gecko1_9':mc,'ie10':nc,'ie11':oc,'ie8':pc,'ie9':Zb,'safari3':Xb,'safari4':fb,'safari5':Ub};j[qc]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(rc)!=-1}())return _b;if(function(){return a.indexOf(Tb)!=-1&&(b>=fb&&b<Ub)}())return Wb;if(function(){return a.indexOf(Tb)!=-1&&(b>=Xb&&b<Ub)}())return Yb;if(function(){return a.indexOf(Tb)!=-1&&(b>=Zb&&b<Ub)}())return $b;if(function(){return a.indexOf(fc)!=-1||b>=Ub}())return hc;return bb};i[qc]={'gecko1_8':V,'ie10':W,'ie8':Nb,'ie9':lc,'safari':mc};j[sc]=function(){var a=tc+bb+uc;var b=tc+bb+vc+bb+wc;var c=o.location.href;var d=xc+o.encodeURIComponent(c);d+=yc+o.encodeURIComponent(a);d+=zc+o.encodeURIComponent(b);var e=new Image;e.src=Ac+bb+Bc+bb+Cc+bb+Dc+bb+Ec+bb+Fc+d;var f=o.navigator.userAgent.toLowerCase();if(f.indexOf(Gc)!=-1||f.indexOf(Hc)!=-1){return Ic}if(f.indexOf(Jc)!=-1){return Jc}if(f.indexOf(Kc)!=-1||f.indexOf(Lc)!=-1){return Kc}return Mc};i[sc]={'linux':V,'mac':W,'unknown':Nb,'windows':lc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};calculator.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};calculator.__computePropValue=k;o.__gwt_activeModules[S].bindings=calculator.__getPropMap;r(O,Nc);if(q()){return D(Oc)}var l;try{alert(Pc);return;var m=l.indexOf(Qc);if(m!=-1){h=parseInt(l.substring(m+W),fb);l=l.substring(V,m)}}catch(a){}calculator.__softPermutationId=h;return D(l+Rc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(Sc);b.setAttribute(Tc,Uc);b.setAttribute(Vc,D(a));p.getElementsByTagName(ob)[V].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(Wc,P);c(Xc);c(Yc);r(Wc,Zc)}
B();calculator.__moduleBase=C();t[S].moduleBase=calculator.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==$c||o.location.protocol==_c);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=ad;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=bd;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(cd+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+dd]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,Zc);A(H);return true}
calculator.succeeded=calculator();